import {expect,mock,test} from 'claude-code/testing';
import {createState,act,tick,snapshot} from '../src/timer-core.js';
const BASE={plugin:'focus-cat-companion',surface:'terminal',component:'AbovePrompt',viewport:{columns:80,rows:30,isFullscreen:false},props:{hasSurvey:false,isWorking:false,maxRows:4,bodyColumns:40,scroll:{offset:0,bodyRows:4},view:{}}} as const;
function setup(on,commands=[],mockUI=true){const store=new Map(),runtime=new Map(),clock=mock.clock(on),writes=[],controls={tool:null,other:null};on('state.get',($,e)=>({value:runtime.get(e.key)||{value:undefined,version:0}}));on('state.set',($,e)=>{const v=runtime.get(e.key)||{version:0};if(e.ifVersion!==undefined&&e.ifVersion!==v.version)return{value:{isSet:false,version:v.version}};const version=v.version+1;runtime.set(e.key,{value:e.value,version});return{value:{isSet:true,version}};});on('store.get',($,e)=>({value:store.get(e.key)}));on('store.set',($,e)=>{store.set(e.key,e.value);writes.push(e.key);return{value:undefined}});on('session.id',()=>({value:'isolated-waiting-test'}));on('command.list',()=>({value:commands}));on('command.register',()=>({value:{command:'focus-cat'}}));on('session.start',()=>({cwd:'/isolated'}));on('session.end',()=>({sessionId:'isolated-waiting-test'}));on('turn.start',($,e)=>({turnId:e.turnId}));on('turn.complete',($,e)=>({text:e.answer}));on('turn.abort',()=>({value:undefined}));on('turn.step',async function*($,e){yield {kind:'text',index:0,text:'original streamed answer'};return{turnId:e.turnId,index:e.index,answer:'original streamed answer',toolUses:[],stopReason:'end_turn',usage:null};});on('tool.call',($,e)=>controls.tool?controls.tool($,e):({result:{original:true},text:'original tool result'}));on('classic.PermissionRequest',()=>({}));on('classic.PostToolUse',()=>({}));on('classic.PostToolUseFailure',()=>({}));on('classic.PermissionDenied',()=>({}));on('prompt.submit',($,e)=>({text:e.text}));if(mockUI)on('ui.render',()=>controls.other||({type:'Box',props:{height:0},children:[]}));return{store,clock,writes,runtime,controls};}
const ref={plugin:'focus-cat-companion',key:'companionRuntime',id:'isolated-waiting-test'} as const;
async function start($){return $.session.start({surface:'terminal',isInteractive:true,cwd:'/isolated'});}
test('initial idle raster replaces the empty engine core reference, without starting a timer',async($,on)=>{
 // TestEngine has no native paint/core bottom. Use the documented opaque core
 // shape from ui.render, rather than the old height-zero Box substitution.
 const{clock,store,runtime,writes}=setup(on,[],false);on('ui.render',()=>({type:'engine',ref:0}));await start($);const ui=await $.ui.mount(BASE);
 expect(await ui.find({type:'Text',text:/25:00/})).toBeDefined();expect(await ui.find({type:'Raster'})).toBeDefined();
 expect((await ui.drawn()).props.height).toBe(4);expect(runtime.get('companionRuntime').value.active).toBe(false);expect(store.size).toBe(0);
 await clock.advance(10000);expect(writes.length).toBe(0);await ui.unmount();
});
test('official mock host UI uses four raster rows; timer and mocked turn walking run independently',async($,on)=>{const{clock,store,runtime}=setup(on);await start($);const ui=await $.ui.mount(BASE);expect(await ui.find({type:'Text',text:/25:00/})).toBeDefined();expect(await ui.find({type:'Raster'})).toBeDefined();await $.command.run({command:'focus-cat',args:'restart'});await clock.advance(2000);expect(store.get('timer:isolated-waiting-test').remaining).toBe(1498000);expect(runtime.get('companionRuntime').value.active).toBe(false);await $.command.run({command:'focus-cat',args:'pause'});await ui.redraw({...BASE.props,isWorking:true});await $.turn.start({turnId:'a',text:'sample prompt'});const before=runtime.get('companionRuntime').value.x;await clock.advance(960);expect(runtime.get('companionRuntime').value.x).not.toBe(before);expect(store.get('timer:isolated-waiting-test').status).toBe('paused');await ui.redraw({...BASE.props,isWorking:false});const out=await $.turn.complete({turnId:'a',answer:'untouched answer',durationMs:1,isAborted:false,reason:'answer'});expect(out.text).toBe('untouched answer');await ui.unmount();});
test('approval wait freezes; original tool result passes; denied approval and stream step recover',async($,on)=>{const{clock,runtime,controls}=setup(on);await start($);const ui=await $.ui.mount({...BASE,props:{...BASE.props,isWorking:true}});await $.turn.start({turnId:'a',text:'sample'});let release,entered;const reached=new Promise(r=>entered=r);controls.tool=async(dollar,e)=>{await $.classic.PermissionRequest({tool_name:'Bash',tool_input:{command:'mock only'}});entered();return await new Promise(r=>release=r)};const resultPromise=$.tool.call({tool:'Bash',command:'mock only',tool_use_id:'x'});await reached;expect(runtime.get('companionRuntime').value.waiting).toContain('Bash');const x=runtime.get('companionRuntime').value.x;await clock.advance(3000);expect(runtime.get('companionRuntime').value.x).toBe(x);release({result:{stdout:'kept',stderr:'',interrupted:false},text:'kept'});expect((await resultPromise).text).toBe('kept');await clock.advance(480);expect(runtime.get('companionRuntime').value.waiting.length).toBe(0);const stream=$.turn.step({turnId:'a',index:1,model:'mock',messageCount:0});expect((await stream.next()).value.text).toBe('original streamed answer');const end=await stream.next();expect(end.done).toBe(true);expect(end.value.answer).toBe('original streamed answer');controls.tool=async()=>{await $.classic.PermissionRequest({tool_name:'Bash',tool_input:{command:'mock failure'}});throw Error('mock tool failure')};let failure;try{await $.tool.call({tool:'Bash',command:'mock failure',tool_use_id:'failed'})}catch(error){failure=error}expect(failure).toBeDefined();expect(failure.message).toContain('no implementation for tool.call');expect(runtime.get('companionRuntime').value.waiting.length).toBe(0);await ui.unmount();});
test('completion reasons stop, subagent/stale completion cannot stop main; no prompt rewrite',async($,on)=>{const{runtime}=setup(on);await start($);const ui=await $.ui.mount({...BASE,props:{...BASE.props,isWorking:true}});for(const reason of ['answer','aborted','error','refusal']){const turnId='completion-'+reason;await $.turn.start({turnId,text:'kept'});await $.turn.complete({turnId:'child',agentId:'child',answer:'',durationMs:1,isAborted:false,reason:'answer'});expect(runtime.get('companionRuntime').value.active).toBe(true);await ui.redraw({...BASE.props,isWorking:false});await $.turn.complete({turnId,answer:'kept',durationMs:1,isAborted:reason==='aborted',reason,...(reason==='refusal'?{refusal:{category:null,explanation:null}}:{})});expect(runtime.get('companionRuntime').value.active).toBe(false);await ui.redraw({...BASE.props,isWorking:true});}expect((await $.prompt.submit({text:'unchanged typed input'})).text).toBe('unchanged typed input');await ui.unmount();});
test('motion off persists preference, freezes reply, idle performs no store writes; narrow viewport and other bands safe',async($,on)=>{const{clock,writes,store,runtime,controls}=setup(on);await start($);const ui=await $.ui.mount(BASE);const count=writes.length;await clock.advance(10000);expect(writes.length).toBe(count);await ui.redraw({...BASE.props,isWorking:true});await $.turn.start({turnId:'a',text:''});await $.command.run({command:'focus-cat',args:'motion off'});expect(store.get('companion:reduced')).toBe(true);const frozen=JSON.stringify(await ui.drawn());await clock.advance(5000);expect(JSON.stringify(await ui.drawn())).toBe(frozen);for(const width of [0,1,4,7,8,14,15,16,40,80,140])for(const rows of [0,1,2,3,4,9]){await ui.redraw({...BASE.props,isWorking:true,bodyColumns:width,maxRows:rows});const node=await ui.drawn();if(node?.type==='Box'&&node.props.width!==undefined){expect(node.props.height).toBeLessThanOrEqual(Math.min(rows,4));expect(node.props.width).toBe(width);}}const other={type:'Text',props:{},children:['existing companion']};controls.other=other;await ui.redraw(BASE.props);expect(await ui.find({type:'Text',text:'existing companion'})).toBeDefined();await ui.unmount();});
test('host-held reload state and qualified self owner retain timer',async($,on)=>{const{store,runtime,clock}=setup(on,[{name:'focus-cat',plugin:'focus-cat-companion@inline'}]);const held={version:1,phase:'focus',remaining:123456,completed:3,status:'paused',motion:0,visible:true,last:0};store.set('timer:isolated-waiting-test',held);runtime.set('timerRuntime',{value:held,version:1});runtime.set('companionRuntime',{value:{version:1,owner:'previous-module',turnId:'a',active:true,reason:'walking',waiting:['Bash'],tools:[['x','Bash']],x:9,direction:-1,frame:1,reduced:false},version:1});const ui=await $.ui.mount({...BASE,props:{...BASE.props,isWorking:true}});await clock.advance(1);expect(runtime.get('companionRuntime').value.x).toBe(9);expect(runtime.get('companionRuntime').value.waiting).toContain('Bash');expect((await $.command.run({command:'focus-cat',args:'status'})).text).toContain('02:04 focus / paused');await $.classic.PostToolUse({tool_name:'Bash',tool_input:{},tool_response:{},tool_use_id:'x'});expect(runtime.get('companionRuntime').value.waiting.length).toBe(0);expect(store.get('timer:isolated-waiting-test').completed).toBe(3);await ui.unmount();});
test('completion stops without UI masking; stale completion does not stop current turn',async($,on)=>{const{runtime,clock}=setup(on);await start($);for(const reason of ['answer','aborted','error','refusal']){const turnId='current-'+reason;await $.turn.start({turnId,text:'mock only'});await $.turn.complete({turnId:'older',answer:'older',durationMs:1,isAborted:false,reason:'answer'});expect(runtime.get('companionRuntime').value.active).toBe(true);await $.turn.complete({turnId,answer:'kept',durationMs:1,isAborted:reason==='aborted',reason,...(reason==='refusal'?{refusal:{category:null,explanation:null}}:{})});expect(runtime.get('companionRuntime').value.active).toBe(false);expect(runtime.get('companionRuntime').value.reason).toBe(reason);const x=runtime.get('companionRuntime').value.x;await clock.advance(1000);expect(runtime.get('companionRuntime').value.x).toBe(x);}});
test('foreign focus-cat command passes unchanged and performs no companion or timer writes',async($,on)=>{const{runtime,writes}=setup(on,[{name:'focus-cat',plugin:'someone-else'}]);on('command.run',()=>({text:'foreign handler unchanged'}));await start($);expect((await $.command.run({command:'focus-cat',args:'restart'})).text).toBe('foreign handler unchanged');expect(runtime.size).toBe(0);expect(writes.length).toBe(0);});
test('preserved 25/5/15 timer commands and four-focus long break, manual next and no repeated completion',()=>{const s=createState(null,0);let now=0;for(let cycle=1;cycle<=4;cycle++){act(s,'restart',now);for(let i=0;i<150;i++){now+=10000;tick(s,now)}expect(s.completed).toBe(cycle);tick(s,now+1);expect(s.completed).toBe(cycle);act(s,'next',now+2);expect(s.phase).toBe(cycle===4?'long':'short');expect(s.status).toBe('idle');expect(s.remaining).toBe(cycle===4?900000:300000);act(s,'next',now+3);expect(s.phase).toBe('focus');expect(s.remaining).toBe(1500000);}act(s,'restart',now+4);act(s,'pause',now+5);const value=snapshot(s);expect(createState(value,now+6).status).toBe('paused');act(s,'reset',now+7);expect(s.completed).toBe(4);expect(s.remaining).toBe(1500000);});
